apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: {{ .Values.concurrencyPolicy | default "Forbid" }}
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit | default "3" }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit | default "1" }}
  jobTemplate:
    spec:
      backoffLimit: failedJobsHistoryLimit: {{ .Values.backoffLimit | default "0" }}
      template:
        spec:
          containers:
            - name: job
              image: "{{ .Values.image.repository }}:{{ include "app.version" . }}"
              {{- with .Values.args }}
              args:
{{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.command }}
              command:
{{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.env }}
              env:
{{- toYaml . | nindent 16 }}
              {{- end }}
              {{ if or .Values.configmap.enabled .Values.secret.enabled .Values.externalSecrets.enabled }}
              envFrom:
                {{ if .Values.configmap.enabled }}
                - configMapRef:
                    name: {{ include "app.fullname" . }}
                {{ end }}
                {{ if .Values.secret.enabled }}
                - secretRef:
                    name: {{ include "app.fullname" . }}
                {{ end }}
                {{ if .Values.externalSecrets.enabled }}
                - secretRef:
                    name: {{ include "app.fullname" . }}-external
                {{ end }}
              {{ end }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
{{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "app.serviceAccountName" . }}
          restartPolicy: {{ .Values.restartPolicy | default "Never" }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
{{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
{{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
{{- toYaml . | nindent 12 }}
          {{- end }}
