{{- if eq .Values.type "CronWorkflow" }}
{{- if and .Values.cronWorkflow.hooks.enabled (not .Values.cronWorkflow.hooks.url) }}
{{- fail "cronWorkflow.hooks.url is required when cronWorkflow.hooks.enabled is true" }}
{{- end }}
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  {{- with .Values.cronWorkflow.timezone }}
  timezone: {{ . | quote }}
  {{- end }}
  {{- if .Values.cronWorkflow.suspend }}
  suspend: true
  {{- end }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy | default "Forbid" }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit | default "3" }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit | default "3" }}
  workflowSpec:
    entrypoint: cron
    serviceAccountName: {{ include "app.serviceAccountName" . }}
    {{- with .Values.imagePullSecrets }}
    imagePullSecrets:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if .Values.activeDeadlineSeconds }}
    activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
    {{- end }}
    ttlStrategy:
      secondsAfterSuccess: {{ .Values.cronWorkflow.ttlSecondsAfterSuccess | default 180 }}
      secondsAfterFailure: {{ .Values.cronWorkflow.ttlSecondsAfterFailure | default 180 }}
    {{- if .Values.cronWorkflow.hostNetwork }}
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    {{- else }}
    dnsPolicy: ClusterFirst
    {{- end }}
    {{- if .Values.cronWorkflow.hooks.enabled }}
    hooks:
      {{- if .Values.cronWorkflow.hooks.running }}
      running:
        expression: 'workflow.status == "Running"'
        template: hook
      {{- end }}
      {{- if .Values.cronWorkflow.hooks.succeeded }}
      succeeded:
        expression: 'workflow.status == "Succeeded"'
        template: hook
      {{- end }}
      {{- if .Values.cronWorkflow.hooks.failed }}
      failed:
        expression: 'workflow.status == "Failed"'
        template: hook
      {{- end }}
      {{- if .Values.cronWorkflow.hooks.pending }}
      pending:
        expression: 'workflow.status == "Pending"'
        template: hook
      {{- end }}
    {{- end }}
    templates:
    - name: cron
      steps:
      - - name: main
          template: main
    - name: main
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cronWorkflow.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      metadata:
        annotations:
          sidecar.istio.io/inject: "false"
          {{- with .Values.cronWorkflow.podAnnotations }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        labels:
          {{- include "app.podLabels" . | nindent 10 }}
          {{- with .Values.cronWorkflow.podLabels }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
      container:
        name: job
        image: {{ include "app.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        {{- with .Values.command }}
        command:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.args }}
        args:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.env }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if or .Values.configmap.enabled .Values.secret.enabled .Values.externalSecrets.enabled .Values.additionalConfigmap.enabled .Values.additionalSecret.enabled .Values.cronWorkflow.configs }}
        envFrom:
          {{- if .Values.configmap.enabled }}
          - configMapRef:
              name: {{ include "app.fullname" . }}
          {{- end }}
          {{- if .Values.secret.enabled }}
          - secretRef:
              name: {{ include "app.fullname" . }}
          {{- end }}
          {{- if .Values.externalSecrets.enabled }}
          - secretRef:
              name: {{ include "app.fullname" . }}-external
          {{- end }}
          {{- if .Values.additionalConfigmap.enabled }}
          {{- range .Values.additionalConfigmap.names }}
          - configMapRef:
              name: {{ . }}
          {{- end }}
          {{- end }}
          {{- if .Values.additionalSecret.enabled }}
          {{- range .Values.additionalSecret.names }}
          - secretRef:
              name: {{ . }}
          {{- end }}
          {{- end }}
          {{- range .Values.cronWorkflow.configs }}
          - secretRef:
              name: {{ . }}
          {{- end }}
        {{- end }}
        {{- with .Values.cronWorkflow.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
        {{- end }}
    {{- if .Values.cronWorkflow.hooks.enabled }}
    - name: hook
      {{- with .Values.cronWorkflow.hooks.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cronWorkflow.hooks.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      metadata:
        annotations:
          sidecar.istio.io/inject: "false"
        labels:
          {{- include "app.podLabels" . | nindent 10 }}
      script:
        name: send-event-hook
        image: {{ .Values.cronWorkflow.hooks.image | default "curlimages/curl:latest" }}
        command: [sh]
        env:
          - name: PAYLOAD
            value: {{ .Values.cronWorkflow.hooks.payload | default "{}" | quote }}
        resources: {}
        source: |
          set -e
          curl --retry 5 --retry-all-errors {{ if .Values.cronWorkflow.hooks.verbose }}-v -i{{ end }} -w '\n' -X POST -H "Content-Type: application/json" \
          -d "$PAYLOAD" {{ .Values.cronWorkflow.hooks.url | quote }}
    {{- end }}
{{- end }}
