{{- if .Values.externalSecrets.enabled }}
{{- if .Capabilities.APIVersions.Has "external-secrets.io/v1beta1" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}-external
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    {{- toYaml .Values.externalSecrets.secretStoreRef | nindent 84 }}
  target:
    name: {{ include "app.fullname" . }}-external
  data:
    {{- range .Values.externalSecrets.data }}
    - remoteRef:
        key: {{ .key }}
      secretKey: {{ .name }}
    {{- end }}
{{- else if .Capabilities.APIVersions.Has "kubernetes-client.io/v1" }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}-external
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  backendType: {{ .Values.externalSecrets.backendType | default "systemManager" }}
  data:
    {{- range .Values.externalSecrets.data }}
    - key: {{ .key }}
      name: {{ .name }}
    {{- end }}
{{- end }}
{{- end }}
