{{- $imageRepo := .Values.image.repository -}}
{{- $imageTag := .Values.image.tag -}}
{{- $backoffLimit := .Values.backoffLimit -}}
{{- $restartPolicy := .Values.restartPolicy -}}
{{- $fullName := include "fullname" . -}}
{{- range .Values.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $fullName }}-{{ .name }}
  labels:
    app: {{ $fullName }}-{{ .name }}
spec:
  backoffLimit: {{ $backoffLimit }}
  template:
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ $imageRepo }}:{{ $imageTag }}"
{{- with .env }}
          env:
{{ toYaml . | indent 12 }}
{{- end }}
          volumeMounts:
            - name: {{ .name }}
              mountPath: "/data"
              readOnly: true
          envFrom:
            - secretRef:
                name: {{ .name }}
      volumes:
        - name: {{ .name }}
          secret:
            secretName: {{ $fullName }}
      restartPolicy: {{ $restartPolicy }}
{{- end }}
