{{- if .Values.overrides_exporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cortex.overridesExporterFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cortex.overridesExporterLabels" . | nindent 4 }}
    {{- with .Values.overrides_exporter.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.overrides_exporter.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.server.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    {{- include "cortex.overridesExporterSelectorLabels" . | nindent 4 }}
{{- end }}
