apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.service.name | default "http" }}
      port: {{ .Values.service.port | default "5000" }}
      targetPort: {{ .Values.service.name | default "http" }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
