apiVersion: v2
description: A Helm chart for Kubernetes CronJob and Argo Workflows CronWorkflow
icon: https://avatars.githubusercontent.com/u/38965494
name: cronjob
type: application
appVersion: latest
version: v1.0.2
maintainers:
  - email: me@nalbam.com
    name: Jungyoul Yu
