# Default values for sample.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
revisionHistoryLimit: 0

controller:
  kind: Deployment # Deployment or Rollout

analysis:
  enabled: false
  # url: "http://sample-preview:3000/success/98"

imagePullSecrets: []

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: latest

command: []
  # - "aws"
  # - "s3"
  # - "ls"

strategy: {}
  # blueGreen:
  #   activeService: sample
  #   autoPromotionEnabled: true
  #   autoPromotionSeconds: 30
  #   previewService: sample-preview
  # canary:
  #   canaryService: sample-preview
  #   stableService: sample
  #   steps:
  #   - setWeight: 25
  #   - pause:
  #       duration: 10
  #   - analysis:
  #       templates:
  #       - templateName: http-benchmark
  #         clusterScope: true
  #       args:
  #       - name: url
  #         value: http://sample-preview:3000/success/98
  #   - setWeight: 50
  #   - pause:
  #       duration: 10
  #   - setWeight: 75
  #   - pause:
  #       duration: 10

irsa:
  enabled: false
  statement: []
    # - resource: "arn:aws:s3:::irsa-sample"
    #   action:
    #     - "s3:Get*"
    #     - "s3:List*"

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podLabels: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

istio:
  gateway:
    enabled: false

ingress:
  enabled: false
  annotations: {}
    # cert-manager.io/cluster-issuer: "letsencrypt-issuer"
    # kubernetes.io/ingress.class: "nginx"
    # kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: chart-example.local
  path: /
  pathType: Prefix
  tls: []
  #  - secretName: sample-tls
  #    hosts:
  #      - sample.domain.com

preview:
  enabled: false
  annotations: {}
    # cert-manager.io/cluster-issuer: "letsencrypt-issuer"
    # kubernetes.io/ingress.class: "nginx"
    # kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: chart-example.local
  path: /
  pathType: Prefix
  tls: []
  #  - secretName: sample-tls
  #    hosts:
  #      - sample.domain.com

livenessProbe: {}
  # httpGet:
  #   path: /
  #   port: 8080
  # initialDelaySeconds: 3
  # periodSeconds: 10
  # failureThreshold: 3

readinessProbe: {}
  # httpGet:
  #   path: /
  #   port: 8080
  # initialDelaySeconds: 3
  # periodSeconds: 10
  # failureThreshold: 3

resources: {}
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # limits:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  metrics: []
    # - pods:
    #     metricName: container_network_receive_bytes
    #     targetAverageValue: 3k
    #   type: Pods
    # - resource:
    #     name: cpu
    #     target:
    #       averageUtilization: 60
    #       type: Utilization
    #   type: Resource

dnsPolicy: ClusterFirst # ClusterFirst Default

restartPolicy: Always # Always, OnFailure, Never

nodeSelector: {}

tolerations: []

affinity: {}

serviceMonitor:
  enabled: false
  selector:
    release: prometheus-operator
  endpoints:
    - interval: 10s
      path: /metrics
      port: http

env: []
  # - name: MESSAGE
  #   value: "hello world"

configmap:
  enabled: false
  data: {}
    # MESSAGE: "hello world"

secret:
  enabled: false
  data: {}
    # SECRET_MESSAGE: "c2VjcmV0IG1lc3NhZ2U="

externalSecrets:
  enabled: false
  backendType: systemManager
  data: []
    # - key: /k8s/alpha/PASSWORD
    #   name: PASSWORD
