---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "cluster-proportional-autoscaler.fullname" . }}
  namespace: {{ default .Release.Namespace .Values.options.namespace }}
  labels:
    {{- include "cluster-proportional-autoscaler.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cluster-proportional-autoscaler.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "cluster-proportional-autoscaler.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
