{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "fluentd-logzio.fullname" . }}
  labels:
    {{- include "fluentd-logzio.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "fluentd-logzio.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "fluentd-logzio.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
