apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fluentd-logzio.fullname" . }}
  labels:
    {{- include "fluentd-logzio.labels" . | nindent 4 }}
type: Opaque
data:
  logzio-log-listener: {{ .Values.logzio.listener | b64enc }}
  logzio-log-shipping-token: {{ .Values.logzio.token | b64enc }}
