apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.backoffLimit }}
  template:
    spec:
      containers:
        - name: job
          image: "{{ .Values.image.repository }}:{{ include "app.version" . }}"
          {{- with .Values.args }}
          args:
{{- toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.command }}
          command:
{{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.env }}
          env:
{{- toYaml . | indent 12 }}
          {{- end }}
          {{ if or .Values.configmap.enabled .Values.secret.enabled .Values.externalSecrets.enabled }}
          envFrom:
            {{ if .Values.configmap.enabled }}
            - configMapRef:
                name: {{ include "app.fullname" . }}
            {{ end }}
            {{ if .Values.secret.enabled }}
            - secretRef:
                name: {{ include "app.fullname" . }}
            {{ end }}
            {{ if .Values.externalSecrets.enabled }}
            - secretRef:
                name: {{ include "app.fullname" . }}-external
            {{ end }}
          {{ end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      restartPolicy: {{ .Values.restartPolicy | default "Never" }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
      {{- end }}
