{{- $imageRepo := .Values.image.repository -}}
{{- $imageTag := .Values.image.tag -}}
{{- $backoffLimit := .Values.backoffLimit -}}
{{- $restartPolicy := .Values.restartPolicy -}}
{{- $fullName := include "fullname" . -}}
{{- range .Values.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $fullName }}-{{ .name }}
  labels:
    app: {{ $fullName }}-{{ .name }}
    {{- include "app.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ $backoffLimit }}
  template:
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ $imageRepo }}:{{ $imageTag }}"
{{- with .command }}
          command:
{{ toYaml . | indent 12 }}
{{- with .env }}
          env:
{{ toYaml . | indent 12 }}
{{- end }}
      restartPolicy: {{ $restartPolicy }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
{{- end }}
