image:
  repository: opspresso/elasticsearch-snapshot
  tag: latest

schedule: "0 5 * * *"

restart: Never

env: []
  # - name: MESSAGE
  #   value: "hello world"

configmap:
  enabled: false
  data: {}
    # AWS_REGION: ap-northeast-2
    # AWS_BUCKET: elasticsearch-snapshot
    # ES_HOST: http://elasticsearch.domain.com/
    # SNAPSHOT_ENABLE: "true"
    # SNAPSHOT_PREFIX: "snapshot"
    # REMOVE_INDICES_ENABLE: "false"
    # REMOVE_INDICES_DELTA: "40"
    # REMOVE_SNAPSHOT_ENABLE: "false"
    # REMOVE_SNAPSHOT_DELTA: "365"
    # SLACK_CHANNAL: "#sandbox"

secret:
  enabled: false
  data: {}
    # SLACK_TOKEN: "c2VjcmV0IHdvcmxkCg=="
