image:
  repository: opspresso/embulk
  tag: 0.10.14

restart: Never

backoffLimit: 0

command: []
  # - /entrypoint.sh
  # - preview
  # - /data/config.yml

env: []
  # - name: PLUGINS
  #   value: "embulk-input-mysql embulk-output-mysql"

config:
  enabled: false
  data: ""
