apiVersion: v1
appVersion: "v1.0.0"
description: Chaos Mesh® is a cloud-native Chaos Engineering platform that orchestrates chaos on Kubernetes environments.
home: https://chaos-mesh.org
icon: https://raw.githubusercontent.com/pingcap/chaos-mesh/master/static/logo.svg
sources:
  - https://github.com/pingcap/chaos-mesh
name: chaos-mesh
version: v0.1.1
keywords:
  - chaos-engineering
  - resiliency
  - fault-injection
  - kubernetes
  - testing
