{{- if and .Values.ingress.enabled .Values.preview.enabled -}}
{{- $ingressApiIsStable := eq (include "app.ingress.isStable" .) "true" -}}
{{- $ingressSupportsIngressClassName := eq (include "app.ingress.supportsIngressClassName" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "app.ingress.supportsPathType" .) "true" -}}
{{- $fullName := include "app.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $ingressPathType := .Values.ingress.pathType -}}
apiVersion: {{ include "app.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}-preview
  labels:
    app: {{ $fullName }}
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.preview.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and $ingressSupportsIngressClassName .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end -}}
  {{- if .Values.preview.tls }}
  tls:
    {{- range .Values.preview.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.preview.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
              {{- end }}
    {{- end }}
{{- end }}
