{{- if .Values.routing.istio.enabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ include "app.namespace" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.routing.istio.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gateways:
    - {{ include "app.fullname" . }}
    - mesh
  hosts:
    {{- range .Values.routing.hosts }}
    - {{ . | quote }}
    {{- end }}
  http:
    - name: primary
      route:
        - destination:
            host: {{ include "app.fullname" . }}
            port:
              number: {{ .Values.service.port | default "80" }}
{{- end }}
