{{- if .Values.istio.gateway.enabled }}
{{- $serviceName := .Values.service.name -}}
{{- $servicePort := .Values.service.port -}}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  servers:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ .host | quote }}
        {{- end }}
        {{- range .Values.ingress.preview.hosts }}
        - {{ .host | quote }}
        {{- end }}
        {{- range .Values.ingress.stable.hosts }}
        - {{ .host | quote }}
        {{- end }}
      port:
        name: {{ .Values.service.name | default "http" }}
        number: {{ .Values.service.port | default "80" }}
        protocol: HTTP
{{- end }}
