{{- if and ( .Capabilities.APIVersions.Has "networking.istio.io/v1beta1" ) ( .Values.istio.gateway.enabled ) }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "app.fullname" . }}
spec:
  host: {{ include "app.fullname" . }}
  {{- if .Values.istio.canary.subsets }}
  subsets:
    - name: canary
      labels:
        app: {{ include "app.fullname" . }}
    - name: stable
      labels:
        app: {{ include "app.fullname" . }}
  {{- end }}
  {{- with .Values.istio.trafficPolicy }}
  trafficPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
