{{- if and .Values.istio.gateway.enabled .Values.ingress.preview.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "app.fullname" . }}-preview
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  gateways:
    - {{ include "app.fullname" . }}
  hosts:
    {{- range .Values.ingress.preview.hosts }}
    - {{ .host | quote }}
    {{- end }}
  http:
    - name: primary
      route:
      {{- if .Values.istio.canary.subsets }}
        - destination:
            host: {{ include "app.fullname" . }}
            port:
              number: {{ .Values.service.port | default "80" }}
            subset: canary
      {{- else }}
        - destination:
            host: {{ include "app.fullname" . }}-preview
            port:
              number: {{ .Values.service.port | default "80" }}
      {{- end }}
{{- end }}
