{{- if and .Values.istio.gateway.enabled .Values.service.preview.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "app.fullname" . }}-preview
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  hosts:
    {{- range .Values.ingress.preview.hosts }}
    - {{ .host | quote }}
    {{- end }}
  gateways:
    - {{ include "app.fullname" . }}
  http:
    - route:
        - destination:
            host: {{ include "app.fullname" . }}-preview
            port:
              number: {{ .Values.service.port | default "80" }}
{{- end }}
