{{- if .Values.service.stable.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-stable
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: {{ .Values.service.name | default "http" }}
      port: {{ .Values.service.port | default "80" }}
      targetPort: {{ .Values.service.name | default "http" }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
{{- end }}
