name: Build-PR

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  lint-changelog:
    runs-on: ubuntu-latest

    container:
      image: jnorwood/helm-docs:v1.5.0

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Check all charts README.md
        run: sh ./helm-docs.sh
